### ISSUE TITLE
Django 1.10 RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.

### ISSUE THREAD

**Issue by RevolutionTech** [bfirsh/django-ordered-model#100]
In some locations, `reverse` is imported from `django.core.urlresolvers` which in Django 1.10 has been deprecated in favour of `django.urls`:
https://github.com/bfirsh/django-ordered-model/blob/0617d88984cbcc43fb69ba3cd5bfabdcb8444b20/ordered_model/models.py#L3

This causes a warning in Django 1.10 and will cease to work in Django 2.0.

Ref: https://docs.djangoproject.com/en/1.10/ref/urlresolvers/#module-django.urls

**Comment by rpkilby** [comment]
btw - it looks like this issue has been resolved and can now be closed.

**Comment by bfirsh** [comment]
Thanks!
