### ISSUE TITLE
Missing move up down links in OrderedTabularInline

### ISSUE THREAD

**Issue by darbula** [bfirsh/django-ordered-model#102]
As noted in this comment https://github.com/bfirsh/django-ordered-model/commit/20bf5ebbbaa30a7bda3bb379c3302c500f5d4919#comments by cybercase

> Currently _get_order_with_respect_to() returns a list of tuples. This statement fails silently raising an AttributeError.

causing no move up down links in tabular view.

**Comment by iMerica** [comment]
This issue persists for me. See https://github.com/bfirsh/django-ordered-model/pull/110#issuecomment-306967979

**Comment by derek-adair** [comment]
This randomly started happening to me... can't figure out what change I introduced to accomplish it either....

**Comment by shuckc** [comment]
I also have no up/down links when I try and use `OrderedTabularInline` with a Many:1 relationship (no through model required).

Specifically if I visit the "Many" model in the Admin, the buttons are rendered and work.
Visiting the "1" side with the OrderedTabularInline renders the table without up/down links- the 'MOVE' column is present but renders a dash for each item.

**Comment by derek-adair** [comment]
Post mortem:  It was when i used a non-standard primary_key. 

It could have been something with my db state, but it worked when not supplying a primary_key field in my models...

Works for me;
```
class Week(models.Model):
    week_num = models.IntegerField()
class Game(OrderedModel):
    week = models.ForeignKey(Week, related_name="games")
    order_with_respect_to = "week"

    class Meta(OrderedModel.Meta):
        pass
```
Was not working with...
```

class Game(OrderedModel):
    .... same stuff plus....
    my_custom_primary_key = models.IntegerField(primary_key=True, editable=False)
```

**Comment by derek-adair** [comment]
It could have been some kind of weird state that my db was in at the time, i will attempt to track this down at some point this week.

**Comment by shuckc** [comment]
Ah that's the same issue I just patched in #128

**Comment by bfirsh** [comment]
@derek-adair just released @shuckc's fix. lmk if it fixes it for you!

Thanks @shuckc!

**Comment by pursuitofepic** [comment]
Is this in 1.4.3? I'm still getting this. I'm in Django 1.10 and python 2.7. Very basic setup following tutorial. Using OrderedTabularInline and not seeing the move links in the Admin.

**Comment by bfirsh** [comment]
Hmm potentially still an issue. I haven’t got the time to investigate right now but can anyone confirm?

**Comment by OdifYltsaeb** [comment]
Hmmm i found this thread when i started messing with this app also. The up and down arrows are missing if order_with_respect_to is undefined or pointing towards "wrong" model. Or is set to something like "order". 

But that's as far as i am right now. Now i'm getting no reverse match error when rendering these up and down arrows:

```
django.core.urlresolvers.NoReverseMatch: Reverse for 'blog_posts_order_up_inline' with arguments '('8', 15, 'up')' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

I do not understand if it is a bug, lack of documentation (as there is very little documentation in regards, of what should be configured and how to get these up/down arrows in the first place), or me misunderstanding how this package is supposed to be used - or all of those things combined.

**Comment by daniel-andersen** [comment]
@OdifYltsaeb This happens when not overriding the "get_urls" method of your ModelAdmin class:

```
class XxxAdmin(admin.ModelAdmin):
    inlines = (XxxThroughModelInline, )

    def get_urls(self):
        urls = super(XxxAdmin, self).get_urls()
        for inline in self.inlines:
            if hasattr(inline, 'get_urls'):
                urls = inline.get_urls(self) + urls
        return urls
```

**Comment by fgblomqvist** [comment]
Just to clarify @daniel-andersens response:
Nowadays you only need to make sure you inherit from the `OrderedInlineModelAdminMixin` in the admin that is using one of the inlines. No need to override get_urls yourself :)

See the admin integration part of the README (currently the second and third example): https://github.com/bfirsh/django-ordered-model#admin-integration

**Comment by pedroorez** [comment]
I'm having this issue too. I tried using `OrderedInlineModelAdminMixin ` with no success. Am I missing something?

```python
class BaseWidgetLayoutInline(OrderedTabularInline):
    model = WidgetLayoutThroughModel
    fields = ('widget', 'order', 'move_up_down_links',)
    readonly_fields = ('order', 'move_up_down_links',)
    extra = 1
    ordering = ('order',)

@admin.register(Layout)
class LayoutAdmin(OrderedInlineModelAdminMixin, admin.ModelAdmin):
    list_display = ('field1',)
    inlines = (BaseWidgetLayoutInline,)

```

**Comment by abarkat99** [comment]
I had the same issue even when using OrderedInlineModelAdminMixin.
Found that below line in function move_up_down_links may be the one causing issues:-
`order_with_respect_to = obj._get_order_with_respect_to_filter_kwargs(obj) or []`
Potential fix:-
`order_with_respect_to = obj.__class__.objects._get_order_with_respect_to_filter_kwargs(obj) or []`
Not sure as i am a beginner to Django.
