### ISSUE TITLE
Couldn't install django-ordered-model

### ISSUE THREAD

**Issue by Asqiir** [bfirsh/django-ordered-model#118]
What I did:
`python3 -m pip install django-ordered-model` (`python3 -m pip` is the equivalent to `pip3` on my computer)

The traceback I got:
`Collecting django-ordered-model
  Downloading django-ordered-model-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d1idycat/django-ordered-model/setup.py", line 5, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d1idycat/django-ordered-model/`

I got the same error when I downloaded the code here and built it myself.

**Comment by bfirsh** [comment]
Whoopsy - thanks!

**Comment by bfirsh** [comment]
fixed in 1.4.1, now being pushed. thanks for the report!
