### ISSUE TITLE
No Reverse Match with OrderedTabularInline

### ISSUE THREAD

**Issue by madEng84** [bfirsh/django-ordered-model#122]
With Django 1.11.2 i have an error like this:

> Django Version:	1.11.2
> Python Version:    2.7
> Exception Type:	NoReverseMatch
> Exception Value:	
> Reverse for '{app_label}_{model_name}_order_up_inline' not found. 

p.s. Obviously app_label and model_name are substituted from real attrs

If i use django_extensions `show_urls` command i cannot see them in project urls, but i can see the ones of the OrderedModelAdmin i used in the whole admin site

**Comment by madEng84** [comment]
Hi, any news on this issue?

**Comment by shuckc** [comment]
That's the first reverse URL required for OrderedTabularInline.

Most likely you need to add the `get_urls()` aggregation code to your Admin subclass mentioned here: https://github.com/bfirsh/django-ordered-model/blob/master/README.md#admin-integration

**Comment by madEng84** [comment]
Perfect
Thank you.

I think, perhaps, that the reload of the page in the change form (especially if i'm doing some modifications on the instance) is not the best approach.
A JS approach could be better, but the `editable=False` on the ModelField is a big limitation.
Do you think am I wrong?
