### ISSUE TITLE
down() method.

### ISSUE THREAD

**Issue by tomaszgiedziun** [bfirsh/django-ordered-model#124]
Hey, i've noticed that in OrderedModelBase.down() method, ordering_queryset is missing order_by.

**Comment by shuckc** [comment]
Hi tomasz, the down() method query does not need an explicit `order_by clause`, because OrderedModel declares a default sort in the Meta attributes, which is used to default sort all query sets created by the model manager:

```
class OrderedModel(OrderedModelBase):
    order = models.PositiveIntegerField(editable=False, db_index=True)
    order_field_name = 'order'   # THIS LINE

    class Meta:
        abstract = True
        ordering = ('order',)
```
Closing this report
