### ISSUE TITLE
suggestion: move tests out of app

### ISSUE THREAD

**Issue by airtonix** [bfirsh/django-ordered-model#13]
I should probably make this issue ticket when I'm not overtired, but here goes:

With the django packages I create, I normally have the tests package along side the app package. 
The main reason for this is : 
- project integrators don't run "out of project" tests
- app developers will have the tests since they "git clone"
- there exists a simple runtests.py which bootstraps django.conf.settings for the tests.

resources: 
- running tests without a project: http://stackoverflow.com/a/12260597/454615

gah this is me being overtired: I can't find it yet, but I did read a convincing article that discouraged putting the tests for a pluggable django app within the app.

**Comment by derek-adair** [comment]
This is super old and can probably be closed as the test suite is runnable if you have docker... and this issue is almost 4 yrs old w/o action :D
