### ISSUE TITLE
Support for move_top and move_down

### ISSUE THREAD

**Issue by madEng84** [bfirsh/django-ordered-model#132]
Hi, it could be very useful if there were the possibility to add move_top and move_bottom in the change_list.

Thanks for your great work

**Comment by shuckc** [comment]
This has been done on pull-request #65, but needs some work to clean it up and rebase.

**Comment by shuckc** [comment]
As it may need a lot of clicking to "undo" a move_top/move_bottom, it probably should be opt-in on the Admin class too.
