### ISSUE TITLE
2.1 version is still incompatible with Django 2.1, already fixed in master

### ISSUE THREAD

**Issue by guilro** [bfirsh/django-ordered-model#162]
https://github.com/bfirsh/django-ordered-model/commit/11385644e46d2f37e8eaf4c5d03dacdd04c50b91 introduces necessary changes OrderedModelAdmin to be compatible with Django 2.1, but fails to introduce the same change for OrderInlineMixin. OrderInlineMixin is still incompatible with Django 2.1, generating an exception at ChangeList \_\_init__.

https://github.com/bfirsh/django-ordered-model/commit/05178cad0ef0b61130e04b2cd6e993ffa0b9a642, solves the problem, but a new release seems necessary as soon as possible to fix the bug.

**Comment by guilro** [comment]
Closing this issue as you seem to be already aware regarding the history or PRs.

**Comment by imomaliev** [comment]
@guilro I will hopefully finish this PR https://github.com/bfirsh/django-ordered-model/pull/161 in next couple of days and we will release new version
