### ISSUE TITLE
next and previous

### ISSUE THREAD

**Issue by Speedy1991** [bfirsh/django-ordered-model#167]
In a current project i need the behaviour of `next` and `previous`.
This should be easy to implement and i'll create a PR if you are interested in

**Comment by imomaliev** [comment]
@Speedy1991 Hi, there is already PR https://github.com/bfirsh/django-ordered-model/pull/111, which will soon be merged

**Comment by Speedy1991** [comment]
Oh, i didn't search in the PR's - only in the issues :)
