### ISSUE TITLE
Template error when using move_up_down_links with OrderedTabularInline

### ISSUE THREAD

**Issue by hughtopping** [bfirsh/django-ordered-model#169]
- Django version 2.1
- Python version 3.6.5
- django-ordered-model version 2.1.0

I am having problems getting the `move_up_down_links` field to work in an `OrderedTabularInline`. When the `move_up_down_links` field is omitted from both `readonly_fields` and `fields`, the admin page loads as expected (but without the buttons to allow re-ordering). However with `move_up_down_links` present, the admin page gives the following error on page load:

```
Template error:
In template /Users/<redacted>/.virtualenvs/<redacted>/lib/python3.6/site-packages/django/contrib/admin/templates/admin/edit_inline/tabular.html, error at line 56
   Reverse for '<app>_<model>_order_up_inline' not found. '<app>_<model>_order_up_inline' is not a valid view function or pattern name.
```
The problem only occurs using `OrderedTabularInline` or `OrderedStackedInline`. If I create an `OrderedModelAdmin`, I'm able to use the `move_up_down_links` without any errors.

Here is a sample code snippet:

```python
from django.db import models
from ordered_model.models import OrderedModel
from ordered_model.admin import OrderedTabularInline
from django.contrib import admin


class Book(models.Model):
    name = models.CharField(max_length=256)


class Section(OrderedModel):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    order_with_respect_to = "book"


class SectionInline(OrderedTabularInline):
    model = Section
    readonly_fields = ("order", "move_up_down_links")
    fields = ("name", "order", "move_up_down_links")
    ordering = ("order",)


class BookAdmin(admin.ModelAdmin):
    inlines = [SectionInline]


admin.site.register(Book, BookAdmin)
```

Any guidance on where I'm going wrong very much appreciated - thank you!

**Comment by imomaliev** [comment]
@hughtopping You forgot to add `OrderedInlineModelAdminMixin` to your admin https://github.com/bfirsh/django-ordered-model#admin-integration
