### ISSUE TITLE
Order nulled on creation

### ISSUE THREAD

**Issue by codingjoe** [bfirsh/django-ordered-model#17]
Hi,

I realized that the order field doesn't increment on when you create new instances inside an empty table using Django admin.

I haven't fully debuged it yet,  the code seems correct on first glimpse. If I increment a value manually and then add some more instances everything works just fine.

Anyone else having that problem on other DBMs maybe? I'm using sqlite3.

Cheers,
Joe

**Comment by shuckc** [comment]
I don't think this is a problem anymore, no similar reports in 2+ years
