### ISSUE TITLE
Feature Request: First & Last

### ISSUE THREAD

**Issue by Speedy1991** [bfirsh/django-ordered-model#178]
In a current project i need first() and last() as methods on OrderedModel.
I don't know if this is needed in this package, but i can provide a PR + tests if you are interested in

**Comment by Speedy1991** [comment]
Eh yea, that is exactly how i patch my first and last methods :)
As i said - I'm not sure if this would be an enhancement for the package - because it's just a wrapper.

I just expected i can do `obj.first()` and `obj.last()`, like i can do with `obj.next()` and `obj.previous()`

**Comment by imomaliev** [comment]
It doesn't make sense to have such methods on instance, because they are not instance aware.

**Comment by bfirsh** [comment]
Agreed it doesn’t make sense to have these methods. Perhaps we could document the correct way.

**Comment by Speedy1991** [comment]
Thanks for clarification :)

**Comment by Speedy1991** [comment]
What is the best way to get the latest of each `order_with_respect_to`?

`get_ordering_queryset()` is only working on instances and not on class base.

Currently i have an ugly workaround with multiple queries:

```
types = Model.objects.values_list("type", flat=True).distinct()
models = []

for t in types :
   policy = Model.objects.filter(type=t).first()
   models .append(policy.get_ordering_queryset().last())
```
