### ISSUE TITLE
Compatibility Matrix for Django < 2.0 is incorrect

### ISSUE THREAD

**Issue by rafagarciac** [bfirsh/django-ordered-model#187]
Hi! n the [Version and Compatibility with Django and Python Table](https://github.com/bfirsh/django-ordered-model/tree/master#compatibility-with-django-and-python) there are some mistakes, because I tried to setup this package in Django 1.8 with Python 2.7 and according to this table I should pick django-ordered-model version 2.1.x, but when I run the server on django (`python manage.py runserver`) I get an error in the next import:
https://github.com/bfirsh/django-ordered-model/blob/bfc133e13507635123282953dd1857bfcea73e21/ordered_model/admin.py#L7
For the other hand, I also tried downgrade one version from 2.1.x to 2.0.x but I get the same error in the same line...
In my point of view there are 2 approaches:
### 1. Change the Version Compatibilities Table (Actual and Wrong Version):

|django-ordered-model version | Django version      | Python version
|-----------------------------|---------------------|--------------------
| **2.1.x**                   | **1.x**             | **2.7** to **3.6**
| **2.0.x**                   | **1.x**             | **2.7** to **3.6** 

### 2. Change this import on each version
According to [Django Documentation v1.8](https://docs.djangoproject.com/en/1.8/ref/urlresolvers/#reverse)
We should change from:  
`from django.urls import reverse`
To:
`from django.core.urlresolvers import reverse `

**Comment by MuriloVAtaide** [comment]
Noticed the same issue here while trying to add it to a django 1.8 project.
The documentation should be updated, it is misleading as is now.

**Comment by Speedy1991** [comment]
1) The docs should be fixed, yes
2) Python2.7 support ends with 2020 - better update now ;)

**Comment by shuckc** [comment]
If you found a specific version that works on Django <2.0 I am happy to update the documentation, otherwise it remains the best guess we have.
