### ISSUE TITLE
IntegrityError when changing ordering to negative number

### ISSUE THREAD

**Issue by davidcorbin** [bfirsh/django-ordered-model#191]
When changing the order of an object with the `.to(<position>)` method, if a negative index is passed there is a database IntegrityError.

```python
def update(self, request, *args, **kwargs):
    instance = self.get_object()
    partial = kwargs.pop('partial', False)
    serializer = self.get_serializer(instance, data=request.data, partial=partial)
    serializer.is_valid(raise_exception=True)
    self.perform_update(serializer)
    if "order" in request.data and instance.order != request.data["order"]:
        instance.to(request.data["order"])
    return Response(serializer.data)
```

If `request.data["order"]` is a negative number, the following error occurs: `django.db.utils.IntegrityError: new row for relation "api_modelname" violates check constraint "api_modelname_order_check"`

**Comment by shuckc** [comment]
In `OrderedModel`, we use a `PositiveIntegerField` to store the position. 
You can either change the type of that field, by using `OrderedModelBase` and setting your own field, or perhaps more sensibly avoid using negative numbers for the position. If you use the relative movement methods `up`, `down` this should not occur. 

See https://github.com/bfirsh/django-ordered-model/blob/86126927aa98b482013f6e38fb9d76c6c088d224/ordered_model/models.py#L315
