### ISSUE TITLE
Inline Admin not working when combined with polymorphic

### ISSUE THREAD

**Issue by Speedy1991** [bfirsh/django-ordered-model#192]
Is there a known issue about the inline orderable is not displayed when it is used on a polymorphic model?

Model:
`class Element(PolymorphicModel, OrderedModel)`

In Admin:
```
class ElementAdmin(OrderedTabularInline, PolymorphicParentModelAdmin)
    ordering = ('order',)
    readonly_fields = ("move_up_down_links",)
```

The inlines won't display the up/down links.
I am not sure how this is connected - because as soon as i remove the polymorphic it is working fine. Any idea, what could collide there?

**Comment by shuckc** [comment]
No known issues, and not enough here to reproduce it. Feel free to reopen if you can provide a more complete example.
