### ISSUE TITLE
Reserved keyword "order" should not be name of column

### ISSUE THREAD

**Issue by quorth0n** [bfirsh/django-ordered-model#197]
This means that raw SQL queries cannot be performed for ordered models. Queries such as the following: `UPDATE [table] SET order = 1 WHERE id = 3;` will fail.

**Comment by Speedy1991** [comment]
You always can escape it. In psql you can simple wrap it in double quotes.
Django's ORM is doing this under the hood too.

**Comment by shuckc** [comment]
I don't consider this a bug. Field names in raw SQL should be escaped. Alternatively you can name the ordering field to a value of your choosing per https://github.com/bfirsh/django-ordered-model#custom-ordering-field
