### ISSUE TITLE
Latest refactor release (3.2/3.3) doesn't work with model inheritance

### ISSUE THREAD

**Issue by mands** [bfirsh/django-ordered-model#204]
Have updated to the latest release and have found that model inheritance doesn't seem to work as previously. Given two models as follows,

```python
from ordered_model.models import OrderedModel

class A(OrderedModel):
    x = models.CharField(default=True)

    class Meta(OrderedModel.Meta):
        ordering = ("order",)

class B(A):
    class Meta:
        proxy = True
```

When creating an object of class `B` via the new manager, an instance of class `A` is instantiated. I can see this when using `django-rest-framework`, which creates the model object as follows,

```python
    instance = ModelClass._default_manager.create(**validated_data)
```

where `ModelClass` is `B` and `default_manager` is now a `OrderedModelManager`, which internally has an `OrderedManagerQuerySet` whose model parameter is `A`.

**Comment by imomaliev** [comment]
@mands Hi, thanks for reporting. Unfortunately I will be able look into this only on next weekend, we are open to accept help. So if you can fix this yourself I will help you merge this.

**Comment by felix-engelmann** [comment]
I have probably the same problem with a different symptom.
Using a generic Create or Update form, saving a derived Model of an OrderedModel fails with:
```
...
  File "...lib/python3.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "...lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File ".../apps/app/views.py", line 445, in form_valid
    validation = super(MyCreateView, self).form_valid(form)
  File "...lib/python3.7/site-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "...lib/python3.7/site-packages/django/forms/models.py", line 458, in save
    self.instance.save()
  File "...lib/python3.7/site-packages/ordered_model/models.py", line 203, in save
    order = self.get_ordering_queryset().get_next_order()
  File "...lib/python3.7/site-packages/ordered_model/models.py", line 186, in get_ordering_queryset
    return qs.filter_by_order_with_respect_to(self)
AttributeError: 'QuerySet' object has no attribute 'filter_by_order_with_respect_to'
```

My models are:
```python
class Property(OrderedModel):
    name = models.CharField(max_length=100)

class AProperty(Property):
    hidden = models.BooleanField(default=False)
```
and I want to update `AProperty`

**Comment by iMerica** [comment]
Related: https://github.com/bfirsh/django-ordered-model/issues/206

**Comment by mands** [comment]
Closing issue - I've managed to resolve this by removing `order_class_path` on the base model (`A` in the example above). 

I think this issue is an edge-case when combining ordering on a base model with derived proxy models (`B` above) - as they all resolve to the same table anyway it's fine to remove `order_class_path` in this particular situation.

**Comment by RevolutionTech** [comment]
As many others on here, I ran into an issue with the refactor releases. In my case, I was combining `OrderedModel` with another base model class that gave me some other behaviour. It looked something like this:
```python
class MyModel(FooModel, OrderedModel):
    name = models.TextField()
    ...
```

My error was:
```
AttributeError: 'FooQuerySet' object has no attribute 'filter_by_order_with_respect_to'
```

My issue was similar to @felix-engelmann's, but I couldn't use the `OrderedModelManager` directly because I also needed the behaviour from the `FooModel`'s default manager.

### Solution

I ended up creating a class to combine the `QuerySet` classes and a combined `Manager` class to provide the combined `QuerySet`:
```python
class OrderedFooQuerySet(FooQuerySet, OrderedModelQuerySet):
    pass

class OrderedFooManager(FooManager, OrderedModelManager):
    _queryset_class = OrderedFooQuerySet

...

class MyModel(FooModel, OrderedModel):
    name = models.TextField()
    ...
    objects = OrderedFooManager()
```

I hope that helps someone else with a similar issue!

**Comment by mogoh** [comment]
I ran into a similar issue.
I wanted to use parler combined with ordered-model.
Thanks to @RevolutionTech I used this solution:


~~~python
from ordered_model.models import OrderedModel
from ordered_model.models import OrderedModelQuerySet
from ordered_model.models import OrderedModelManager
from parler.managers import TranslatableQuerySet
from parler.managers import TranslatableManager
from parler.models import TranslatableModel
from parler.models import TranslatedFields


class TranslatableOrderdQuerySet(TranslatableQuerySet, OrderedModelQuerySet):
    pass

class TranslatableOrderedManager(OrderedModelManager, TranslatableManager):
    _queryset_class = TranslatableOrderdQuerySet
~~~


~~~python
from ordered_model.models import OrderedModel
from parler.models import TranslatableModel
from utils.managers import TranslatableOrderedManager

class PersonTitle(TranslatableModel, OrderedModel):
    objects = TranslatableOrderedManager()
    # ....
~~~

**Comment by iMerica** [comment]
I have Django Ordered Model working with inheritance in production (using `PolymorphicModel` and `OrderedModel`), but it required lots of overriding and customization. Also, this customization was 100% specific to my particular use case.

YMMV.
