### ISSUE TITLE
formset for inline form seems to be ignored

### ISSUE THREAD

**Issue by remort** [bfirsh/django-ordered-model#207]
Hi there!

```
class ProgramCourseFormSet(forms.models.BaseInlineFormSet):
    def clean(self):
        raise forms.ValidationError('An error')

@admin.register(lesson.Program)
class ProgramAdmin(OrderedInlineModelAdminMixin, admin.ModelAdmin):
    class ProgramCourseInline(OrderedTabularInline):
        formset = ProgramCourseFormSet
        model = lesson.ProgramCourse
        min_num = 1
        extra = 1
        list_display = ('move_up_down_links', 'title', 'order')
        readonly_fields = ('order', 'move_up_down_links',)
        ordering = ('order',)
    list_display = ('pk', 'title')
    inlines = [ProgramCourseInline]
```

This code should fire up an error every time i try to save object with ordered inline form. But it doesn't happen. I need to validate inline m2m form before sending to the server. How can I do that ?

**Comment by shuckc** [comment]
What do you mean by 'before sending to the server'? There is no javascirpt/client-side validation in the Django Admin, and none in this library. You code example doesn't include `ProgramCourseInline`, the model, and it is not really possible to help without this information.
