### ISSUE TITLE
Django 3.0 compatibility

### ISSUE THREAD

**Issue by sergei-maertens** [bfirsh/django-ordered-model#208]
Hey, I was trying out to use django-ordered-model while updating our project boilerplate to be Django 3.0 compatible.

This project imports `django.utils.six`, which was removed in 3.0. I haven't checked if there are any other issues, but replacing `django.utils.six` with `six` OR dropping Python 2 support (Python 2.7 is EOL after all ;) ) would both be fixes.

Which approach has your preference?

**Comment by imomaliev** [comment]
There is no six usage in this project. Please, try newer version.
