### ISSUE TITLE
query on child model returns parent objects when order_class_path is set to parent model

### ISSUE THREAD

**Issue by zainsattar-avomd** [bfirsh/django-ordered-model#216]
class BaseQuestion(OrderedModel):
    order_class_path = __module__ + '.BaseQuestion'
    question = models.TextField(max_length=100)

    class Meta:
        ordering = ('order',)

class MultipleChoiceQuestion(BaseQuestion):
    good_answer = models.TextField(max_length=100)
    wrong_answer1 = models.TextField(max_length=100)
    wrong_answer2 = models.TextField(max_length=100)
    wrong_answer3 = models.TextField(max_length=100)

class OpenQuestion(BaseQuestion):
    answer = models.TextField(max_length=100)

In this example the following query always returns a queryset of BaseQuestions when i query MultipleChoiceQuestion/OpenQuestion.objects

**Comment by Audiotuete** [comment]
For some reason it kills inheritance completely. No "OpenQuestion" objects are created in the database. Even if you use OpenQuestion.save() a "BaseQuestion" object is created. So the query can only return "BaseQuestion" objects. I noticed this when my admin templates complained that there is no ptr_id field on my child classes...
