### ISSUE TITLE
MPTT with OrderedModel

### ISSUE THREAD

**Issue by gam-phon** [bfirsh/django-ordered-model#23]
When using django-mptt with django-ordered-model. I have some problems.
First:
This problem happens when saving an instance
**Manager isn't accessible via [Model] instances***
After checking the problem I have found that is line is causing the problem
in model > get_ordering_queryset function

```
qs = qs or self._default_manager.all()
```

I have seen MPTT code they change the default manager to a special manager called TreeManager.

If I change the code to this 

```
qs = qs or self._tree_manager.all()
```

or this one

```
qs = qs or [Model]._tree_manager.all()
```

it will work. I am sorry if I could not help more than that.

Beside this is my order of inheritance in the model
class Name(MPTTModel, OrderedModel)

**Comment by shuckc** [comment]
This won't work without a custom ModelManager implementation, and it does not make much sense to have two independent orderings over the same objects. Closing as invalid.
