### ISSUE TITLE
inline OrederedModelAdmin

### ISSUE THREAD

**Issue by fariza** [bfirsh/django-ordered-model#25]
Hello

First, thanks for the great model.

The fact that we can do SubsetOrdering is very useful, but it becomes a problem to administrate, because there is no an INLINE OrderedModelAdmin.

I am not very strong in django internals, so I prefer not to offer my help, it will be more a problem than anything else. 

Thanks again
Federico

**Comment by Nekmo** [comment]
+1

**Comment by pcompassion** [comment]
+1

wouldn't it be a good starting point to create an InlineOrderedModelAdmin with move_up_down_links, and find a way to stuff that in django's inline template by extending?

**Comment by mverleg** [comment]
This is solved, right?

**Comment by fariza** [comment]
It's been a long time since I used it. I can not say if this was added or not.

Thanks

**Comment by mverleg** [comment]
There's `OrderedTabularInline` which I think matches the description, if I understand correctly :+1:

**Comment by fariza** [comment]
In that case, thanks for the great work
