### ISSUE TITLE
Add Python 3 to CI builds and testing

### ISSUE THREAD

**Issue by leo-the-manic** [bfirsh/django-ordered-model#27]
Whether intentionally or unintentionally, this lightweight library works out of the box with Python 3 (haven't tested the admin, just the core ordering). However, to feel comfortable using this  project going forward, I have to know that Python 3 will have formal support. If there is interest in this I will take the time to make a pull request to add formal Python 3 support (whether that's changing the Travis config or fixing possible admin issues in Python 3 or whatever it may take). Please let me know what you think.

**Comment by bfirsh** [comment]
Done! https://github.com/bfirsh/django-ordered-model/pull/63
