### ISSUE TITLE
Options.module_name has been deprecated in favor of model_name

### ISSUE THREAD

**Issue by pryankster** [bfirsh/django-ordered-model#30]
(Discovered this issue while trying to switch to mysql-connector from SQLite3.)

Apparently, _meta.module_name is going away, to be replaced by _meta.model_name.  There are a couple of instances of _meta.module_name in the ordered-model code which should be replaced with model_name ... HOWEVER, that may break backward compatibility with older (1.5?) django.

django bug referring to deprecation:
https://code.djangoproject.com/ticket/19689

(mysql-connector has a bug where all warnings are considered errors if DEBUG = True, so it turned up this warning as an error
http://bugs.mysql.com/bug.php?id=71806)

**Comment by bfirsh** [comment]
Fixed in #53!
