### ISSUE TITLE
Pip install git+ don't pull templates

### ISSUE THREAD

**Issue by Lagovas** [bfirsh/django-ordered-model#40]
When execute pip install git+...., templates will not pulled and when look on sources in github, he show that "this path skips through empty directories".  Maybe i do something wrong? But django doesn't see this templates too and in package this templates not exists too.

**Comment by mverleg** [comment]
As of now I can't reproduce the problem (anymore?), so I think it can be closed. It seems to have been solved in a3681a326446c238e71f22bc20cff8940279a289

**Comment by bfirsh** [comment]
:+1:
