### ISSUE TITLE
django 1.7 support?

### ISSUE THREAD

**Issue by YAmikep** [bfirsh/django-ordered-model#41]
Hi,

Does this app fully support Django 1.7?
I am trying django-ordered-model==0.4.0 and there is a Deprecated warning:

```
/venv/local/lib/python2.7/site-packages/ordered_model/admin.py:19: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  model=self.model._meta.module_name)
```

It's not a big issue since it's just a warning but I am wondering whether there is something else I should be aware of when using it with django 1.7?

Thanks

**Comment by bfirsh** [comment]
Fixed in #53!
