### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by palm86** [bfirsh/django-ordered-model#57]
Since Django 1.8 has been released, it would be nice to have a PyPI release of django-ordered-model that is compatible with Django 1.8.

**Comment by bfirsh** [comment]
0.4.1 is. :)

**Comment by bfirsh** [comment]
Oh wait maybe it isn't. Hm. Sorry.

**Comment by bfirsh** [comment]
Done :)

**Comment by palm86** [comment]
Wonderful, thanks!
