### ISSUE TITLE
Admin integration: moving fails if the object has a `move` field

### ISSUE THREAD

**Issue by Mitranim** [bfirsh/django-ordered-model#59]
The title is self-explanatory. The `OrderedModelAdmin.move_view()` method tries to call the `OrderedModel.move()` method, which fails if the model has a field named `move`. The same might happen for `up`, `down` or any other fields that could clash with `OrderedModel`'s methods.

**Comment by Zopieux** [comment]
Namespacing \o/

**Comment by shuckc** [comment]
Django has the same limitation: it will not let you have a field called `filter`, `save` or `delete`, although you can name a field and then force the database column be the reserved word. We have more methods that could clash with field names, but you could do the same trick to keep nice database column names if needed.

The reserved names for an OrderedModel are:

- get_ordering_queryset
- move _deprecated_
- move_down _deprecated_
- move_up _deprecated_
- swap
- up
- down
- to
- above
- below
- top
- bottom
- order (use OrderedModelBase if you need to rename this)
