### ISSUE TITLE
order_with_respect_to causes additional _order field and ignores original order field

### ISSUE THREAD

**Issue by gbezyuk** [bfirsh/django-ordered-model#60]
`order_with_respect_to` causes additional `_order` field creation and ignores original `order` field.
Probably the `order` field name used here should be changed to `_order`, as django itself does.

**Comment by smcoll** [comment]
@gbezyuk did you declare `order_with_respect_to` on the model's Meta class?  That's Django's implementation; this package's implementation refers to an attribute of the same name, but directly on the model.

**Comment by shuckc** [comment]
This ticket (and the linked issue) don't make any sense, closing.
