### ISSUE TITLE
Admin URL config deprecation

### ISSUE THREAD

**Issue by mcwebb** [bfirsh/django-ordered-model#73]
Hi, thanks for a really great module.
Just thought I should report (since it doesn't seem to have been reported yet), I'm getting the following deprecation warning for this module.

```
[...]/site-packages/ordered_model/admin.py:32:
RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10.
Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='{app}_{model}_order_down'.format(**self._get_model_info())),
```

**Comment by timgraham** [comment]
PR: https://github.com/bfirsh/django-ordered-model/pull/75

**Comment by emontellese** [comment]
Should this issue be closed?

(I noted this issue as well with the pip-installed version).  

Great app!

**Comment by mcwebb** [comment]
The PR doesn't seem to have been merged yet. Not sure why - seems good to
me.

**Comment by emontellese** [comment]
Oh right!  (New to github)

**Comment by alexshin** [comment]
Please merge pr #75
