### ISSUE TITLE
Admin Integration many-to-many relationship issue

### ISSUE THREAD

**Issue by Madalosso** [bfirsh/django-ordered-model#77]
hey, i just try to run a project with the examples copied from documentation and it raises this error:

`AttributeError at /admin/ord/pizza/add/
'Manager' object has no attribute 'get_query_set'`

my models.py and admin.py are both exactly copied from docs.

**Comment by elementgreen** [comment]
I was getting this too and was able to fix it by changing the following line in ordered_model/admin.py source in the OrderedTabularInline class' get_queryset method (at line 177 in my version).
From:
qs = cls.model._default_manager.get_query_set()

To:
qs = cls.model._default_manager.get_queryset()

I suspect this has to do with a deprecation of Manager.get_query_set() with newer versions of Django.

**Comment by tjwudi** [comment]
@elementgreen is right, thank you. I don't suggest modifying source directly though. You could also just override this method directly before it gets fixed :)

**Comment by Madalosso** [comment]
i agree, thank you for the answer.
in the end i'm not longer needing the functionality of order, i am using another strategy to solve the problem, but i hope this topic help someone :)
