### ISSUE TITLE
'Manager' object has no attribute 'get_query_set'

### ISSUE THREAD

**Issue by madEng84** [bfirsh/django-ordered-model#80]
The problem is in Line 177 of _admin.py_ module
Can you fix this? On Pypi too? (django-ordered-model==1.1.0)

Thanks in advance

**Comment by javcasas** [comment]
#81 That's the expected fix.

**Comment by orzel** [comment]
The bug is still present in the last django-ordered-model you get through pypi. I'm using django 1.8

It indeed seems like admin.py handle get_query_set/get_queryset in all places but on this line 177.

**Comment by bfirsh** [comment]
Should be fixed in #94. Just about to release a new version. :)
