### ISSUE TITLE
swap method seems to take an model instance but use a queryset

### ISSUE THREAD

**Issue by avoiney** [bfirsh/django-ordered-model#90]
Hi,

The docstring of the `swap` method speaks of object but the method definition get `qs` (queryset??):

```
def swap(self, qs):
    """
    Swap the positions of this object with a reference object.
    """
```

The documentation (in the README) says

```
foo = Item.objects.create(name="Foo")
bar = Item.objects.create(name="Bar")
### Swap positions
foo.swap(bar)
```

BUT, in the code, the swap method try to get the first element of the qs (queryset??) argument.
A solution could be to use a `isinstance(qs, QuerySet)` check to handle both of the case.
The other is to rewrite the docstring and the documentation to reflect the actual code.

Thanks in advance,
Regards,

**Comment by filipeximenes** [comment]
Also don't understand why would someone pass a queryset.
