### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by mjholtkamp** [bfirsh/django-ordered-model#91]
Hi!

First of all, thanks for this awesome package! I was thinking about implementing something like this and when I looked to see if someone else implemented this, I found your project and it's exactly what I needed.

There is a small thing that bugs me and that's already fixed in #73, but it has not been released on PyPi yet.

Could you release a new version so I don't have this warning anymore?

Thanks in advance!

**Comment by cdobbyn** [comment]
+1 - Agree with above. Thanks

**Comment by mcassiano** [comment]
+1 PyPi reports version 1.1.0 but the warning is still there :/

**Comment by halfnibble** [comment]
We need PyPi version 1.1.1, please! 
(With #73 )

**Comment by cdobbyn** [comment]
@bfirsh - Can haz new release?!

**Comment by bfirsh** [comment]
Done! Sorry for slowness!
