### ISSUE TITLE
`to()` not updating all indices request.POST

### ISSUE THREAD

**Issue by robmoggach** [bfirsh/django-ordered-model#96]
I'm using the `to()` method and it's not updating all the object indices as expected. I have a number of images that are limited in order scope using `order_with_respect_to " ("album",)`. When I use the `to()` method to move an object to a new location, not all objects are updated properly. Subsequently I have multiple objects with the same order index.

Specifically I'm using a `jquery.ajax` `POST` request to change the order of some images in a gallery. I send `image_id` and `new_order` via `POST` to a view that finds the image `image=Image.objects.get(id=image_id)` and then calls `image.to(new_order)`. Only the image in question is updated. 

> **In the django shell calling the same commands works as expected.**

```
>>> from gallery.models import Image
>>> Image.objects.all()
[
    <Image: Gallery Image: 0-change-01>,
    <Image: Gallery Image: 1-change-02>,
    <Image: Gallery Image: 2-change-03>,
    <Image: Gallery Image: 3-change-04>
]
>>> Image.objects.all()[1].to(0)
>>> Image.objects.all()
[
    <Image: Gallery Image: 0-change-02>, 
    <Image: Gallery Image: 1-change-01>, 
    <Image: Gallery Image: 2-change-03>, 
    <Image: Gallery Image: 3-change-04>
]
```

**I've tidied up the list display above so it's more readable on github**

Here's my view code... pretty basic stuff:

```
def image_order(request):
    if request.method == 'POST':
        response = {}
        image_id=request.POST.get('imageid')
        new_order=request.POST.get('neworder')
        try:
            image = Image.objects.get(id=image_id)
        except Image.DoesNotExist:
            response = {'message': 'Image not found, yo.'}
            return HttpResponse( json.dumps(response), content_type="application/json" ) #404
        image.to(new_order)
        response = {
            'message': 'Image #{id} moved to  {neworder} successfully!'.format(id=image_id, neworder=new_order),
        }
        return HttpResponse( json.dumps(response), content_type="application/json" ) #200
    else:
        return HttpResponse( json.dumps({"Err": "that didn't work"}), content_type="application/json") #400


```

**Comment by robmoggach** [comment]
working through debugging this - it's seemingly random so i'm working through the `to()` method to see if I can solve it - may be an asynchronous, transaction, something??

**Comment by robmoggach** [comment]
OK - so the following line never evaluates to `True` for my ajax calls

    if getattr(self, self.order_field_name) > order

Seems to be a typing issue and forcing the values to integers using `int()` fixes the issue. It needs to be tested further to confirm. TBD if this is view side or needs to be fixed in the app.

**Comment by robmoggach** [comment]
Confirmed that I can get it working by using `int()` on the view side. It's probably worth having a type check built in to stop this behavior or just force `order` attributes to integers. Leaving this open for discussion.

**Comment by shuckc** [comment]
Hi Rob,
From what you describe you were calling `object.to(_str_)` due to a bug in the view? I can see how this might be surprising on Python 2.7, silently bad ordering:

```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 12 > "10"
False
```
>>> 

It's not a problem on Python 3 - we would propagate the `TypeError` and hit Django's error page:

```
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 12 > "10"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: int() > str()
>>> 
```

I don't think it's worth complicating the code only for 2.7, since that is reducing in useage.
